image:
  repository: authelia/authelia
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

# https://www.authelia.com/docs/configuration/secrets.html
# env:
#   TZ: Europe/Madrid
#   AUTHELIA_JWT_SECRET_FILE: /app/secrets/jwt_secret
#   AUTHELIA_SESSION_SECRET_FILE: /app/secrets/session_secret

service:
  port:
    port: 9091

# initContainers:
# - name: init-redis
#   image: busybox:1.33
#   command: ['sh', '-c', "until nslookup redis.<namespace>.svc.cluster.local; do echo waiting for redis; sleep 2; done"]

# additionalVolumes:
#   - name: secrets
#     secret:
#       secretName: authelia
#       items:
#       - key: jwt_secret
#         path: jwt_secret
#       - key: session_secret
#         path: session_secret

# additionalVolumeMounts:
#   - name: secrets
#     mountPath: /app/secrets
#     readOnly: true

persistence:
  config:
    enabled: false
    emptyDir: false
    # existingClaim: authelia-config

# securityContext:
#   runAsGroup: 1001
#   runAsUser: 1001

# podSecurityContext:
#   fsGroup: 1001