image:
  repository: jacobalberty/unifi
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

env:
  RUNAS_UID0: "false"
  UNIFI_STDOUT: "true"

securityContext:
  capabilities:
    add:
      - SETFCAP

probes:
  liveness:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /status
        port: https
        scheme: HTTPS
      initialDelaySeconds: 30
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 10

  readiness:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /status
        port: https
        scheme: HTTPS
      initialDelaySeconds: 30
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 10

service:
  type: LoadBalancer
  externalIPs:
    - 192.168.2.30
  externalTrafficPolicy: Local
  port:
    port: 8443
    name: https
  additionalPorts:
    - port: 8080
      name: http

  additionalServices:
    - enabled: true
      nameSuffix: tcp
      type: LoadBalancer
      externalIPs:
        - 192.168.2.30
      externalTrafficPolicy: Local
      port:
        port: 8880
        name: http-redirect
      additionalPorts:
        - port: 8843
          name: https-redirect
        - port: 6789
          name: speedtest
    - enabled: true
      nameSuffix: udp
      type: LoadBalancer
      externalIPs:
        - 192.168.2.30
      externalTrafficPolicy: Local
      port:
        port: 3478
        protocol: UDP
        name: stun
      additionalPorts:
        - port: 5514
          protocol: UDP
          name: syslog
        - port: 10001
          protocol: UDP
          name: discovery
        - port: 1900
          protocol: UDP
          name: l2

persistence:
  unifi:
    enabled: false
    mountPath: /unifi
