image:
  repository: redis
  pullPolicy: IfNotPresent

service:
  port:
    name: redis
    port: 6379

persistence:
  data:
    enabled: false
    emptyDir: false
    mountPath: /data
    # existingClaim: redis-data

# securityContext:
#   runAsGroup: 1001
#   runAsUser: 1001

# podSecurityContext:
#   fsGroup: 1001